### ISSUE TITLE
PLATEAUインポート作業前の確認事項

### ISSUE THREAD

**Issue by mapconcierge** [yuuhayashi/citygml-osm#104]
# コミュニティへの事前告知(案)
 * [ ] [MLIT PLATEAU/imports outline｜OSM Wiki](https://wiki.openstreetmap.org/wiki/JA:MLIT_PLATEAU/imports_outline#%E3%83%81%E3%83%BC%E3%83%A0%E6%B4%BB%E5%8B%95%E8%A8%88%E7%94%BB) に作業用のアカウントを事前告知する。
 * [ ] 作業ログ用の Issue を [yuuhayashi/citygml-osm Issues｜GitHub](https://github.com/yuuhayashi/citygml-osm/issues) に作成する。
 * [ ] [OSM Japan Slack](https://bit.ly/OSM_Japan) の **#01_アナウンスと告知** チャンネルでインポート前に事前に作業を行う周知を行う。
 * [ ] [OSM Japan Slack](https://bit.ly/OSM_Japan) の **#30_プログラムとデータ利用** チャンネルでインポート前に事前に作業を行う周知を行う。
 * [ ] [Facebook Japan Community](https://www.facebook.com/groups/158469420871592) でインポート前に事前に作業を行う周知を行う。
 * [ ] [OSM Japan Slack](https://bit.ly/OSM_Japan) の **#01_アナウンスと告知** チャンネルでインポート前に事前に作業を行う周知を行う。
 * [ ] [talk-ja ML](https://lists.openstreetmap.org/listinfo/talk-ja) に事前に作業を行う周知を行う。
 * [ ] [talk:MLIT PLATEAU/imports outline 討論履歴](https://wiki.openstreetmap.org/wiki/JA_talk:MLIT_PLATEAU/imports_outline#%E8%A8%8E%E8%AB%96%E5%B1%A5%E6%AD%B4) を熟読し、特に [反対・懸念のご意見](https://wiki.openstreetmap.org/wiki/JA_talk:MLIT_PLATEAU/imports_outline#%E5%8F%8D%E5%AF%BE%E3%83%BB%E6%87%B8%E5%BF%B5%E3%81%AE%E3%81%94%E6%84%8F%E8%A6%8B) について、反対される方の気持ちを汲み取った上で、OSMマッパーの心が折れないように最大限の配慮を行う方針であることを理解する。
 * [ ] できれば、 **#OSMjp** ハッシュタグをつけて各種SNSで情報拡散する。告知とともに協力者も募る。
